---
title: "final_project analysis"
author: "carrie lu"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1.  Load Libraries
```{r}
library(ggplot2)
library(tidyverse)
library(janitor)
library(jpeg)
library(shiny)
library(shinydashboard)
library(naniar)
library(shinythemes)
library(RColorBrewer)
library(paletteer)
library(ggthemes)
library(dplyr)
library(viridis)
```

2.  Read in data:
```{r}
conservatory <- read_csv("conservatory_modified.csv") %>% clean_names()
conservation_status <- read_csv("filtered_data2.csv") %>% clean_names()
```

3.  Look at data
```{r}
glimpse(conservatory)
names(conservatory)
glimpse(conservation_status$group)
names(conservation_status)
```
filter for plants
IUCN_Plants+Non_IUCN_Vascular_Plants
```{r}
#filtered_data <- conservation_status %>%
 # filter(group %in% c("IUCN_Plants", "Non_IUCN_Vascular_Plants"))%>%
  #rename(scientific_name = binomial) %>%
  #select(-common_name, -total_area,- small_range, -name_language, -datanam_area,-datanam_pct_area, -small_range, -iso_a3)%>%
  #distinct()

  glimpse(conservatory)

conservatory_cleaned2 <- conservatory  %>%
  select(-latest_update,-synonym, -plant_source, -date_brought_in, -variety_hybrid) %>%
  filter(scientific_name != "NA") %>% 
  filter(genus != "NA") %>%
  filter(species != "NA") %>% 
  mutate(scientific_name = paste(genus, species, sep = " "))%>%
  filter(scientific_name != "Unknown") %>%
  filter(scientific_name != "NA") %>%
  distinct()

```

for the upload
```{r}
#write.csv(filtered_data, "plant_conservation.csv", row.names = FALSE)
#didn't work

#filtered_data2 <- conservation_status %>% filter(group %in% c("IUCN_Plants", "Non_IUCN_Vascular_Plants"))%>% mutate(scientific_name = binomial) %>% select(-common_name, -name_language, -binomial, -group, -iucn_id_no,-iso_a3)%>% distinct()

#write.csv(filtered_data2, "filtered_data2.csv", row.names = FALSE)
```

```{r}
#merge
merged_data <- merge(conservatory_cleaned2, conservation_status, by = "scientific_name")

nrow(conservatory_cleaned2)

nrow(merged_data)

tail(merged_data)
names(merged_data)
head(merged_data)
```


```{r}
#counts of each IUCN category
table(merged_data$iucn_category)

```

```{r}
merged_data %>%
  mutate(match_status = case_when(
    native_country == wb_datanam ~ "Match",
    TRUE ~ "Mismatch"
  )) %>%
  count(match_status)
```
**(Native countries in the two datasets don't match)



```{r}
color_palette <- c("CR" = "red", "EN" = "orange", "VU" = "yellow", "NT" = "chartreuse", "LC" = "darkgreen", "DD" = "grey")

ui <- fluidPage(
  titlePanel("IUCN Categories for Selected Family"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput("family", "Select Family", choices = unique(merged_data$family))
    ),
    mainPanel(
      plotOutput("plot", width = "600px", height = "500px")
    )
  )
)

# Define server logic
server <- function(input, output) {
  output$plot <- renderPlot({
    family_data <- merged_data %>%
      filter(family == input$family) %>%
      group_by(iucn_category) %>%
      summarise(count = n())
    
    # Create the bar plot with specified colors and legend
    ggplot(family_data, aes(x = iucn_category, y = count, fill = iucn_category)) +
      geom_bar(stat = "identity", show.legend = TRUE) +
      scale_fill_manual(values = color_palette, name = "IUCN Category") +  # Add legend title
      labs(title = paste("IUCN Categories for", input$family),
           x = "Category",
           y = "Count") +
      theme(axis.text.x = element_text(angle = 45, hjust = 1))
  })
}

# Run the application
shinyApp(ui, server)


```


heat map?
```{r}

glimpse(merged_data)
merge_cleaned<- merged_data %>%
  rename(region=wb_datanam)%>%
  filter(wb_iso != "NA")%>% #remove regions that aren't countries
  select("iucn_category", "region") 


mapdata <- map_data("world")
mapdata <- left_join(mapdata, merge_cleaned, by="region")

ggplot(mapdata, aes(x = long, y = lat, group = group)) +
  geom_polygon(aes(fill = iucn_category), color = "black") +
  scale_fill_manual(name = "IUCN Category", values = color_palette) +
  labs(x = "Longitude", y = "Latitude", title = "Map with IUCN Categories") +
  theme_minimal()+
  theme(aspect.ratio = .6)  # Adjust the aspect ratio here

ggsave("map_plot.png", plot, dpi = 300)

```
