---
title: "BIS015L Final Project"
author: "Elisabeth Sellinger"
date: "2024-02-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Load Libraries
```{r}
library(ggplot2)
library(tidyverse)
library(janitor)
library(jpeg)
```

2. Read in data:
```{r}
conservatory <- read_csv("conservatory_data.csv") %>% clean_names()
```

3. Look at data
```{r}
glimpse(conservatory)
names(conservatory)
```
±=
4. Look at NAs
```{r}
conservatory %>% 
  map_df(~ sum(is.na(.)))
```

5. Clean data:
```{r}
conservatory_cleaned <- conservatory %>% 
  mutate(region = native_region) %>% 
  select("accession_num", "region") %>% 
  filter(region != "NA") %>% 
  filter(region != "Multiple Countries") %>% 
  filter(region != "Unknown")
```

```{r}
conservatory_cleaned1 <- conservatory_cleaned %>% 
  group_by(region) %>% 
  summarise(n_samples = n()) %>% 
  mutate(n_samples = n_samples)
```

6. Call map data:
```{r}
mapdata <- map_data("world") ##ggplot2
```

7. Join datasets:
```{r}
mapdata <- left_join(mapdata, conservatory_cleaned1, by="region")
```

8. Remove unneeded regions
```{r}
# mapdata1<-mapdata %>% filter(!is.na(mapdata$n_samples))
```

9. Plot it!
```{r}
map1<-ggplot(mapdata, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = n_samples), color = "black")
map1
```
10. Make it pretty:
```{r}
map2 <- map1 + scale_fill_gradient(name = "Number of Samples", low = "lightblue", high =  "olivedrab", na.value = "grey90") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank()) +
  labs(title = "UC Davis Conservatory Data by Region")
map2 
```

